-- ========================================================
-- KIM DOWOOK AI Portfolio - Supabase Database Schema
-- Supabase SQL Editor에서 전체 선택 후 Run 하시면 테이블 및 초기 데이터가 생성됩니다.
-- ========================================================

-- 1. 프로필 (소개) 테이블 생성
CREATE TABLE IF NOT EXISTS public.profiles (
    id INT PRIMARY KEY DEFAULT 1,
    name TEXT NOT NULL,
    headline TEXT NOT NULL,
    bio TEXT NOT NULL,
    interests JSONB DEFAULT '[]'::jsonb,
    tech_stack JSONB DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 프로필 RLS (Row Level Security) 설정 및 공개 접근 정책 부여
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read profiles" ON public.profiles;
CREATE POLICY "Allow public read profiles" ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert profiles" ON public.profiles;
CREATE POLICY "Allow public insert profiles" ON public.profiles FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update profiles" ON public.profiles;
CREATE POLICY "Allow public update profiles" ON public.profiles FOR UPDATE USING (true);


-- 2. 프로젝트 (작업물) 테이블 생성
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    tags JSONB DEFAULT '[]'::jsonb,
    demo_url TEXT,
    github_url TEXT,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 프로젝트 RLS 설정 및 공개 접근 정책 부여
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read projects" ON public.projects;
CREATE POLICY "Allow public read projects" ON public.projects FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert projects" ON public.projects;
CREATE POLICY "Allow public insert projects" ON public.projects FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update projects" ON public.projects;
CREATE POLICY "Allow public update projects" ON public.projects FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete projects" ON public.projects;
CREATE POLICY "Allow public delete projects" ON public.projects FOR DELETE USING (true);


-- 3. 초기 포트폴리오 기본 데이터 삽입 (기존 데이터가 없을 시)
INSERT INTO public.profiles (id, name, headline, bio, interests, tech_stack)
VALUES (
    1,
    '김도욱',
    'AI 기술로 새로운 경험을 만드는 개발자, 김도욱입니다.',
    '경기도 고양시에서 AI 트렌드를 탐구하며 사용자 중심의 최첨단 AI 웹사이트 및 앱 서비스를 개발하고 있습니다. 유용하고 감각적인 AI 경험을 선사하는 것이 저의 개발 목표입니다.',
    '["AI 트렌드 연구", "AI 웹앱 개발", "서비스 런칭 & 데모"]'::jsonb,
    '["OpenAI API", "Python", "React", "Next.js", "Vite", "Vanilla JS", "Tailored CSS"]'::jsonb
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.projects (id, title, description, tags, demo_url, github_url, image_url)
VALUES 
(
    1,
    '🤖 AI 운세 쿠키 생성기',
    '오늘의 운세와 용기를 북돋아 주는 격언을 Generative AI가 맞춤 생성해 주는 웹 서비스',
    '["#GPT-4o", "#JavaScript", "#Web Audio", "#CSS3"]'::jsonb,
    'https://example.com/fortune',
    'https://github.com/example/fortune',
    'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=60'
),
(
    2,
    '🎨 AI 캔버스 그림 해석기',
    '캔버스에 그린 그림과 이미지를 AI가 실시간으로 분석하고 심도 있게 해석해 주는 멀티모달 AI 서비스',
    '["#VisionAI", "#Gemini", "#Canvas", "#React"]'::jsonb,
    'https://ai.studio/apps/a6e6ef17-d596-4692-b76c-bd0169136f4a?fullscreenApplet=true',
    'https://github.com/example/canvas-ai',
    'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&auto=format&fit=crop&q=60'
),
(
    3,
    '🎨 AI 시각 이미지 갤러리 & 프롬프트 생성기',
    '원하는 이미지 스타일을 프롬프트 명령어로 변환하고 실시간 렌더링을 돕는 유틸리티 웹앱',
    '["#Midjourney", "#DALL-E3", "#Vite", "#CSS Glass"]'::jsonb,
    'https://example.com/gallery',
    'https://github.com/example/gallery',
    'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=800&auto=format&fit=crop&q=60'
)
ON CONFLICT (id) DO NOTHING;
