-- ========================================================
-- KIM DOWOOK AI Portfolio - Supabase 원클릭 전용 초기화 & 연동 스크립트
-- Supabase SQL Editor에서 전체 선택(Ctrl+A) 후 'Run' 버튼을 클릭해주세요.
-- ========================================================

-- 1. 기존 데이터 및 테이블 완전 초기화 (Clean Reset)
DROP TABLE IF EXISTS public.projects CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- 2. 프로필 (소개) 테이블 생성
CREATE TABLE public.profiles (
    id INT PRIMARY KEY DEFAULT 1,
    name TEXT NOT NULL,
    headline TEXT NOT NULL,
    bio TEXT NOT NULL,
    interests JSONB DEFAULT '[]'::jsonb,
    tech_stack JSONB DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. 프로젝트 (작업물) 테이블 생성
CREATE TABLE public.projects (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    tags JSONB DEFAULT '[]'::jsonb,
    demo_url TEXT,
    github_url TEXT,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. RLS (Row Level Security) 및 외부 접근 허용 정책 설정
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all" ON public.profiles FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all" ON public.profiles FOR UPDATE USING (true);

CREATE POLICY "Enable read access for all" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all" ON public.projects FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all" ON public.projects FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all" ON public.projects FOR DELETE USING (true);

-- API 역할 권한 부여
GRANT ALL ON public.profiles TO anon, authenticated, service_role;
GRANT ALL ON public.projects TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;

-- 5. 초기 포트폴리오 기본 데이터 자동 등록
INSERT INTO public.profiles (id, name, headline, bio, interests, tech_stack)
VALUES (
    1,
    '김도욱',
    'AI 기술로 새로운 경험을 만드는 개발자, 김도욱입니다.',
    '경기도 고양시에서 AI 트렌드를 탐구하며 사용자 중심의 최첨단 AI 웹사이트 및 앱 서비스를 개발하고 있습니다. 유용하고 감각적인 AI 경험을 선사하는 것이 저의 개발 목표입니다.',
    '["AI 트렌드 연구", "AI 웹앱 개발", "서비스 런칭 & 데모"]'::jsonb,
    '["OpenAI API", "Python", "React", "Next.js", "Vite", "Vanilla JS", "Tailored CSS"]'::jsonb
);

INSERT INTO public.projects (id, title, description, tags, demo_url, github_url, image_url)
VALUES 
(
    1,
    '🤖 AI 운세 쿠키 생성기',
    '오늘의 운세와 용기를 북돋아 주는 격언을 Generative AI가 맞춤 생성해 주는 웹 서비스',
    '["#GPT-4o", "#JavaScript", "#Web Audio", "#CSS3"]'::jsonb,
    'https://example.com/fortune',
    'https://github.com/example/fortune',
    'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=60'
),
(
    2,
    '🎨 AI 캔버스 그림 해석기',
    '캔버스에 그린 그림과 이미지를 AI가 실시간으로 분석하고 심도 있게 해석해 주는 멀티모달 AI 서비스',
    '["#VisionAI", "#Gemini", "#Canvas", "#React"]'::jsonb,
    'https://ai.studio/apps/a6e6ef17-d596-4692-b76c-bd0169136f4a?fullscreenApplet=true',
    'https://github.com/example/canvas-ai',
    './assets/images/anime_robot_canvas.png'
),
(
    3,
    '🎓 대학생 창업 성향 테스트하기!',
    '대학생들의 창업 성향과 잠재력을 다각도로 분석하여 맞춤형 창업 유형 및 가이드를 제공하는 테스트 웹 서비스',
    '["#Vite", "#React", "#Startup", "#Vercel"]'::jsonb,
    'https://holymoly-orpin.vercel.app/',
    'https://github.com/example/startup-test',
    './assets/images/startup_test_thumb.png'
);

-- 시퀀스 동기화
SELECT setval(pg_get_serial_sequence('public.projects', 'id'), COALESCE((SELECT MAX(id) FROM public.projects), 1));

-- 성공 메시지 반환
SELECT '✅ Supabase 데이터베이스 테이블 및 초기 데이터 설정 완벽 완료!' AS status;
